<div style="
    background-color: #7BAFD4;
    border-radius: 18px;
    padding: 22px 26px;
    display: flex;
    align-items: center;
    gap: 24px;
    margin-bottom: 18px;
">
    <img src="592_avatar_lr.png" alt="GEOG 592"
        style="width:110px;height:110px;border-radius:22px;">
    <div>
        <div style="
            font-family: Impact, 'Arial Black', Arial, sans-serif;
            font-size: 42px;
            font-weight: 900;
            letter-spacing: 2px;
            line-height: 1;
            color: white;
        ">GEOG 592</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 22px;
            font-weight: 700;
            color: #13294B;
            margin-top: 8px;
        ">GIS Programming</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 16px;
            color: #13294B;
            margin-top: 6px;
        ">Module 3, Day 1: pandas, Objects, and DataFrames</div>
    </div>
</div>

# Module 3: Day 1
## pandas Fundamentals — From CSV Rows to DataFrames

Today we move from the `csv` module to **pandas**. We will also pause to explain some Python ideas that will become increasingly common: **classes, objects, attributes, methods, and dot notation**.

### Today you will learn to:
- explain the difference between Python's standard library and an external package
- install and import pandas
- recognize a **class** and an **object**
- distinguish an **attribute** from a **method**
- read dot notation such as `df.head()` and `df.shape`
- read a CSV into a pandas `DataFrame`
- inspect rows, columns, and data types
- select columns and rows
- filter a DataFrame using boolean conditions

## From the `csv` Module to pandas

In Module 2 we used `csv.DictReader()`. Each row became a dictionary, and we wrote loops to inspect or clean the file.

pandas gives us a higher-level structure called a **DataFrame**. A DataFrame is designed for working with tabular data.

The same CSV can therefore be represented in two different ways:

```text
csv module                     pandas
-----------                    ------
list of row dictionaries   ->  DataFrame
row["LocationName"]        ->  df["LocationName"]
loop through rows           ->  operations on entire columns
```

## Installing pandas with `pip`

The `csv` module comes with Python's **standard library**, so it does not need to be installed separately.

`pandas` is an **external package**. If it is not already available in your Python environment, install it with `pip`.

In a Jupyter notebook, the simplest way to do this is:

```python
%pip install pandas
```

> The `%` symbol is important!

You usually only need to install a package once for a particular Python environment.

In [5]:
# Run this only if pandas is not installed in the current environment.
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/Charlotte/Desktop/SeniorYear/GEOG_592/geog592-stromc/geog592-stromc/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/Charlotte/Desktop/SeniorYear/GEOG_592/geog592-stromc/geog592-stromc/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 770.8 kB/s  0:00:12eta 0:00:01
Downloading numpy-2.5.3-cp314-cp314-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 524.4 kB/s  0:00:10 eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.5

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Import pandas

The conventional import is:

```python
import pandas as pd
```

`pd` is simply a short alias for the pandas module.

In [6]:
import pandas as pd

print(pd.__version__)

3.0.5

### Practice 1 — Standard library or external package?

For each item below, decide whether it comes with Python or normally needs to be installed separately.

- `csv`
- `pandas`

Then explain why `import csv` and `import pandas` (or `import pandas as pd`) look similar even though installation is different.

## A Short Introduction to Classes and Objects

You do **not** need to learn object-oriented programming today. You just need the basic concepts to understand code such as:

```python
df.head()
df.shape
df["Data_Value"].mean()
```

Here are the definitions.
- **Class** : a template that defines the kind of data and behavior needed to create an *object*.
- **Object** :  one actual instance created from a class.  Objects in a class have *attributes* and *methods.*
- **Attribute** : refers to specific data that belongs to an object. 
- **Method** : refers to a function that belongs to the object; usually all objects of the same class have the same methods (but the methods' behaviour can depent on the specific attributes)

### Example of a class

The `Point` class defined below represents a point. It stores two attributes (`x` and `y`) and has two methods.

You are **not expected to be able to write a class definition like this on the assessment**. We are using it only to make dot notation visible.

In [7]:
class Point:
    def __init__(self, the_x_value, the_y_value):
        self.x = the_x_value ## here we are creating the x attribute
        self.y = the_y_value ## here we are creating the y attribute

    def show_coordinates(self): ## here we are creating the show_coordinates method
        print(self.x, self.y)

    def move(self, dx, dy): ## here we are creating the move method
        self.x = self.x + dx
        self.y = self.y + dy

The `Point` class has two attributes.

In the next code block, we create two objects from the same `Point` class.

In [8]:
point_a = Point(100, 200)
point_b = Point(300, 450)

print(point_a.x)
print(point_b.x)

100
300

In this example:

| Python element | What is it? |
|---|---|
| `Point` | a class |
| `point_a` | an object |
| `point_b` | another object |
| `x`, `y` | attributes |
| `show_coordinates()` | a method |
| `move()` | another method |

#### Dot notation
The **dot** can be read as "something that belongs to this object."

In [9]:
point_a.show_coordinates()

point_a.move(10, 20)
point_a.show_coordinates()

100 200
110 220

### Attribute vs. method

Look at the difference between these two statements.

```python
point_a.x
point_a.show_coordinates()
```
`x` is an **attribute**. It stores information.
`show_coordinates()` is a **method** that performs an action.

A useful visual clue is that methods are **called with parentheses**.

### Practice reading the dot notation

For each expression, identify the object and name/describe what comes after the dot.

```python
point_b.y
point_b.show_coordinates()
point_b.move(5, -10)
```

Which ones are attributes? Which ones are methods?

The same idea applies to objects that are not GIS features.
This (for some reason) is one of the most common examples given in programming classes: 

```python
class Student:
    def __init__(self, name, score):
        self.name = name
        self.score = score

    def passed(self):
        return self.score >= 70
```

Here, `Student` is the class. Each student created from it is an object.

Notice the same pattern:

- `student1.name` → attribute
- `student1.score` → attribute
- `student1.passed()` → method

> Reminder: You do **not** need to create classes for this module. The purpose is to understand what Python is doing when you later write code such as `df.head()`, `df.shape`, or `df["Data_Value"].mean()`.

In [10]:
class Student:
    def __init__(self, name, score):
        self.name = name
        self.score = score

    def passed(self):
        return self.score >= 70

student1 = Student("Ana", 85)

print(student1.name)
print(student1.score)
print(student1.passed())

Ana
85
True

#### The Dataset

We will continue using the Module 2 file:

```text
physical_NC_with_an_error.csv
```

It contains North Carolina county-level physical inactivity data and includes an intentional bad record. Keeping the same file lets us focus on how pandas changes the workflow.

Place the CSV in the same folder as this notebook.

## Read a CSV into a DataFrame

With pandas, reading the CSV is one line:

```python
df = pd.read_csv("physical_NC_with_an_error.csv")
```

`pd.read_csv()` returns a **DataFrame object**.

In [16]:
filename = "physical_NC_with_an_error1.csv"
df = pd.read_csv(filename)

In [17]:
type(df)

pandas.DataFrame

The important part of the result is `DataFrame`.

So now we can apply the vocabulary from our `Point` example:

```text
pandas.DataFrame   -> class
df                 -> object
head()             -> method
shape              -> attribute
```

## Methods and Attributes of a DataFrame

### `head()` is a method

A method performs an action using the object.

In [18]:
df.head()

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2023,NC,North Carolina,Cleveland,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.2,21.5,31.5,"101,378","78,793",37045,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5554731480207 35.3336676514711)
1,2023,NC,North Carolina,Burke,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.7,22.2,31.5,"88,338","72,201",37023,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.70486114808 35.7494843806822)
2,2023,NC,North Carolina,Alamance,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.7,19.3,28.3,"179,165","139,859",37001,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.3994760246283 36.0436739846115)
3,2023,NC,North Carolina,Beaufort,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.0,21.4,31.0,"44,481","35,939",37013,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-76.8589373781447 35.4941226525086)
4,2023,NC,North Carolina,Caldwell,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,25.5,20.4,30.9,"80,574","64,820",37027,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5466545637271 35.9530956685159)

### `shape` is an attribute

An attribute stores or reports information about the object.

In [19]:
df.shape

(100, 20)

The result has the form:

```text
(rows, columns)
```

Notice that `shape` does **not** use parentheses.

### Practice 3 — Method or attribute?

Classify each of the following using the syntax as a clue.

```python
df.head()
df.tail()
df.shape
df.columns
df.info()
```

## Inspect the DataFrame

Before analyzing a dataset, inspect its structure.

In [20]:
df.head(3)

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2023,NC,North Carolina,Cleveland,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.2,21.5,31.5,"101,378","78,793",37045,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5554731480207 35.3336676514711)
1,2023,NC,North Carolina,Burke,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.7,22.2,31.5,"88,338","72,201",37023,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.70486114808 35.7494843806822)
2,2023,NC,North Carolina,Alamance,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.7,19.3,28.3,"179,165","139,859",37001,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.3994760246283 36.0436739846115)

In [21]:
df.tail(3)

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
97,2023,NC,North Carolina,Forsyth,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.5,20.1,29.2,"392,921","304,926",37067,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.2562678118814 36.1306194708921)
98,2023,NC,North Carolina,Wake,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,17.9,14.8,21.2,"1,190,275","919,538",37183,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-78.6503446201168 35.7900594036584)
99,2023,NC,North Carolina,Macon,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.3,19.7,29.5,"38,412","31,394",37113,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-83.4217780844555 35.1506263752147)

In [22]:
df.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'LocationName', 'DataSource',
       'Category', 'Measure', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Low_Confidence_Limit', 'High_Confidence_Limit',
       'TotalPopulation', 'TotalPop18plus', 'LocationID', 'CategoryID',
       'MeasureId', 'DataValueTypeID', 'Short_Question_Text', 'Geolocation'],
      dtype='str')

In [23]:
df.dtypes

Year                       int64
StateAbbr                    str
StateDesc                    str
LocationName                 str
DataSource                   str
Category                     str
Measure                      str
Data_Value_Unit              str
Data_Value_Type              str
Data_Value               float64
Low_Confidence_Limit     float64
High_Confidence_Limit    float64
TotalPopulation              str
TotalPop18plus               str
LocationID                 int64
CategoryID                   str
MeasureId                    str
DataValueTypeID              str
Short_Question_Text          str
Geolocation                  str
dtype: object

### `info()` combines several structural checks

It reports column names, non-null counts, and data types.

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   100 non-null    int64
 1   StateAbbr              100 non-null    str
 2   StateDesc              100 non-null    str
 3   LocationName           100 non-null    str
 4   DataSource             100 non-null    str
 5   Category               100 non-null    str
 6   Measure                100 non-null    str
 7   Data_Value_Unit        100 non-null    str
 8   Data_Value_Type        100 non-null    str
 9   Data_Value             100 non-null    float64
 10  Low_Confidence_Limit   100 non-null    float64
 11  High_Confidence_Limit  100 non-null    float64
 12  TotalPopulation        100 non-null    str
 13  TotalPop18plus         100 non-null    str
 14  LocationID             100 non-null    int64
 15  CategoryID             100 non-null    str
 16  MeasureId              100 non-null    str
 17  DataValueTypeID        100 non-null    str
 18  Short_Question_Text    100 non-null    str
 19  Geolocation            100 non-null    str
dtypes: float64(3), int64(2), str(15)
memory usage: 15.8 KB

Why are many columns currently shown as `object` rather than numeric types?

(Look at the first record before answering. Remember that the file contains an intentional error.)

## Selecting One Column

Use square brackets and the column name:

```python
df["LocationName"]
```

In [25]:
df["LocationName"].head()

0    Cleveland
1        Burke
2     Alamance
3     Beaufort
4     Caldwell
Name: LocationName, dtype: str

A single DataFrame column is usually a pandas **Series object**.

In [26]:
names = df["LocationName"]
print(type(names))

<class 'pandas.Series'>

This explains another common chain of notation:

```python
df["LocationName"].head()
```

Read it from left to right:

1. `df["LocationName"]` returns a Series object.
2. `.head()` calls a method belonging to that Series.

## Selecting Multiple Columns

Use a **list of column names** inside the brackets.

In [27]:
df[["LocationName", "Data_Value", "TotalPopulation"]].head()

  LocationName  Data_Value TotalPopulation
0    Cleveland        26.2         101,378
1        Burke        26.7          88,338
2     Alamance        23.7         179,165
3     Beaufort        26.0          44,481
4     Caldwell        25.5          80,574

Notice the double brackets:

```python
df[["LocationName", "Data_Value"]]
```

The inner brackets create a list of column names. The outer brackets select those columns from the DataFrame.

## Selecting Rows by Position with `iloc`

`iloc` selects rows and columns by integer position.

```python
df.iloc[0]
```

returns the first row.

In [28]:
df.iloc[0]

Year                                                               2023
StateAbbr                                                            NC
StateDesc                                                North Carolina
LocationName                                                  Cleveland
DataSource                                                        BRFSS
Category                                          Health Risk Behaviors
Measure                  No leisure-time physical activity among adults
Data_Value_Unit                                                       %
Data_Value_Type                                 Age-adjusted prevalence
Data_Value                                                         26.2
Low_Confidence_Limit                                               21.5
High_Confidence_Limit                                              31.5
TotalPopulation                                                 101,378
TotalPop18plus                                                   78,793
LocationID                                                        37045
CategoryID                                                      RISKBEH
MeasureId                                                           LPA
DataValueTypeID                                               AgeAdjPrv
Short_Question_Text                                 Physical Inactivity
Geolocation                  POINT (-81.5554731480207 35.3336676514711)
Name: 0, dtype: object

In [29]:
df.iloc[1:4][["LocationName", "Data_Value"]]

  LocationName  Data_Value
1        Burke        26.7
2     Alamance        23.7
3     Beaufort        26.0

Note from the above can also use `iloc[]` with slice notation to select a range of rows. In this case `1:4` means *include index 1 and everything is between 1 and 4, excluding 4.*

## Boolean Comparisons

A comparison against a pandas column produces a Boolean Series.

In [30]:
df["Year"] == "2023"

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: Year, Length: 100, dtype: bool

The result contains `True` or `False` for every row.

We can store this Boolean Series in a variable called a **mask**.

In [31]:
valid_year = df["Year"] == "2023"
valid_year.head()

0    False
1    False
2    False
3    False
4    False
Name: Year, dtype: bool

## Filtering Rows

Use the Boolean mask inside the DataFrame brackets.

In [32]:
print('length before mask', len(df))
print('length of mask is' ,len(valid_year) ,' and needs to be the same as the length of the df that you want to mask')

clean_year = df[valid_year]

print('length of our new df after using the mask:', len(clean_year))
print('since we had', len(valid_year[valid_year == True]), 'True values')
clean_year.head()

length before mask 100
length of mask is 100  and needs to be the same as the length of the df that you want to mask
length of our new df after using the mask: 0
since we had 0 True values

Empty DataFrame
Columns: [Year, StateAbbr, StateDesc, LocationName, DataSource, Category, Measure, Data_Value_Unit, Data_Value_Type, Data_Value, Low_Confidence_Limit, High_Confidence_Limit, TotalPopulation, TotalPop18plus, LocationID, CategoryID, MeasureId, DataValueTypeID, Short_Question_Text, Geolocation]
Index: []

Here I am going to mask using information from another column. I am going to mask all the rows that have a county name that starts with an A. 
Think of masking like a fast way of doing a looped `if` statement.

In [33]:
mask = df["LocationName"].str.startswith("A", na=False)
df2 = df[mask]
df2

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
2,2023,NC,North Carolina,Alamance,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.7,19.3,28.3,"179,165","139,859",37001,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-79.3994760246283 36.0436739846115)
5,2023,NC,North Carolina,Anson,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,31.7,26.7,37.0,"21,897","17,493",37007,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-80.1026872705448 34.9736529585894)
11,2023,NC,North Carolina,Alexander,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,24.7,20.3,29.9,"36,473","29,341",37003,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.1770332718611 35.9204725331462)
13,2023,NC,North Carolina,Avery,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.8,19.1,28.9,"17,561","15,011",37011,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.9225713884377 36.0766997215744)
14,2023,NC,North Carolina,Ashe,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,23.8,19.4,29.0,"27,063","22,627",37009,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.5005505989795 36.4341479679829)
15,2023,NC,North Carolina,Alleghany,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Age-adjusted prevalence,26.8,21.8,32.9,"11,342","9,426",37005,RISKBEH,LPA,AgeAdjPrv,Physical Inactivity,POINT (-81.1272787621881 36.4916227409052)

One of the most common masking errors is trying to mask a DataFrame using a mask of the wrong dimmension or with different indexing.

## Multiple Conditions

Use `&` for AND when combining pandas Boolean conditions. Put each condition in parentheses.

In [34]:
selected = df[
    (df["Year"] == "2023") &
    (df["StateAbbr"] == "NC")
]

selected[["LocationName", "Data_Value"]].head()

Empty DataFrame
Columns: [LocationName, Data_Value]
Index: []

Later we will see the same idea again in NumPy and GeoPandas. **Boolean filtering is one of the most transferable ideas in the course.**

## Practice — Predict Before Running

What will each expression return: a scalar value, a Series, or a DataFrame?

```python
df["LocationName"]
df[["LocationName", "Data_Value"]]
df.iloc[0]
df[df["Year"] == "2023"]
df.shape
```

Also identify which expressions use dot notation.

## Preparing for Programming Skills Check #3

You should have a general idea of:

- what a **class** and an **object** are;
- the difference between an **attribute** and a **method**;
- reading dot notation such as `df.head()` and `df.shape`;
- `pd.read_csv()`;
- DataFrames and Series;
- `head()`, `shape`, `columns`, and `info()`;
- selecting one or more columns;
- `iloc`;
- Boolean comparisons and using masks;
- filtering rows with one or more conditions.

You will not be asked to write a class from scratch. The class examples are there to help you understand how pandas objects, attributes, and methods work.